config/routes.rb
Rails.application.routes.draw do\

  #sign in 
  get '/sign_in', to: "sessions#sign_in"
  post '/sessions', to: "sessions#create"
  delete '/sessions', to: "sessions#destroy"

  #user specific pages 
  get '/:id/feed', to: 'users#feed', as: "feed"
  get '/:id/activity', to: 'users#activity', as: "activity"
  
  #follow someone
  post "/users/:id", to: "users#back", as: "back"

  #unfollow someone
  post "users/:id/forget", to: "users#forget", as: "forget"
  
  resources :comments
  resources :slaps
  resources :snaps
  resources :genres
  resources :posts
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/back.rb
class Back < ActiveRecord::Base
    belongs_to :backer, foreign_key: "backer_id", class_name: "User"
    belongs_to :backee, foreign_key:"backee_id", class_name: "User"

    def backer_name 
        self.backer.username
    end 

    def backee_name
        self.backee.username
    end 
end 

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user 
    belongs_to :post 

    def user_name
        self.user.username 
    end 

    def post_user_name
        self.post.user.username
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :posts 
    has_many :users, through: :posts 
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :genre
    has_many :comments
    has_many :snaps
    has_many :slaps 
    has_many :backs

    def user_name
        self.user.username
    end 

    def snap_number
        self.snaps.count.to_s
    end 

    def slap_number
        self.slaps.count.to_s
    end 

    def snapped_users
        self.snaps.collect{|snap| snap.user}
    end 

    def snapped_user?(user)
        self.snapped_users.include?(user)
    end 

    def slapped_users
        self.slaps.collect{|slap| slap.user}
    end 

    def slapped_user?(user)
        self.slapped_users.include?(user)
    end
end

app/models/slap.rb
class Slap < ApplicationRecord
    belongs_to :user
    belongs_to :post

    def post_user_name
        self.post.user.username
    end

end

app/models/snap.rb
class Snap < ApplicationRecord
    belongs_to :user
    belongs_to :post

    def post_user_name
        self.post.user.username
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :genres, through: :posts
    has_many :comments
    has_many :snaps
    has_many :slaps 
    has_many :backs
    
    has_many :backer_backs, foreign_key: :backee_id, class_name: "Back"
    has_many :backers, through: :backer_backs, source: :backer

    has_many :backee_backs, foreign_key: :backer_id, class_name: "Back"
    has_many :backees, through: :backee_backs, source: :backee 
    has_secure_password


    def backee_posts
        self.backees.collect{|user| user.posts}.flatten
    end 

    def backed_profile?(profile)
        self.backees.include?(profile)
    end 


end 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticated?
    before_action :current_comment, only: [:edit, :update]

    def create 
        @user.comments.build(content:params[:content],post_id:params[:post_id]).save
        redirect_to post_path(params[:post_id])
    end 

    def edit 
       
        @post = Post.find(@comment.post.id)
    end 

    def update
        # byebug
        @comment.update(comment_params)
        redirect_to post_path(comment_params[:post_id])
    end 

    def destroy 
        Comment.destroy(params[:id])
        redirect_to post_path(params[:post_id])
    end 

    def current_comment
         
        @comment = Comment.find(params[:id])
    end 


    private

    def comment_params 
        params.require(:comment).permit(:content,:id,:post_id)
    end 

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticated?
    before_action :current_post, only: [:show,:edit,:update]

    def index
        @posts = Post.all
    end 

    def show 
    end 

    def new 
        @post = Post.new
    end 

    def create 
        @user.posts.build(post_params).save
        redirect_to user_path(@user)
    end 

    def edit 
    end 

    def update 
        @post.update(post_params)
        redirect_to user_path(session[:id])
    end 

    def destroy 
        Post.destroy(params[:id])
        redirect_to user_path(session[:id])
    end 


    def current_post
        @post = Post.find(params[:id])
    end 

    private

    def post_params
        params.require(:post).permit(:image_url,:description,:genre_id)
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def sign_in
    @disable_nav = true
    @user = User.new 
  end


  def create 
    @user = User.find_by username:user_params[:username]

    if @user && @user.authenticate(user_params[:password]) 
      session[:id] = @user.id
      redirect_to feed_path(@user)

    else 
      flash[:error] = "Incorrect username or password"
      redirect_to sign_in_path
    end 
  end 

  def destroy 
    session.clear
    redirect_to sign_in_path
  end 
  
  def user_params 
    params.require(:user).permit(:username, :password)
  end 
    
end
# Cassatt
# 3766787944

app/controllers/slaps_controller.rb
class SlapsController < ApplicationController
    before_action :authenticated?
   
    def create 
        Slap.find_or_create_by(user_id:@user.id,post_id:params[:post_id])
        redirect_to params[:origin]
    end 

    def destroy
        slap = Slap.find_by(post_id:params[:post_id],user_id:@user.id)
        Slap.destroy(slap.id)
        redirect_to params[:origin]
    end 

end

app/controllers/snaps_controller.rb
class SnapsController < ApplicationController
    before_action :authenticated?
   
    def create 
        Snap.find_or_create_by(user_id:@user.id,post_id:params[:post_id])
        redirect_to params[:origin]
    end 

    def destroy
        snap = Snap.find_by(post_id:params[:post_id],user_id:@user.id)
        Snap.destroy(snap.id)
        redirect_to params[:origin]
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticated?, only: [:feed, :show, :activity]

    def show
        @profile = User.find(params[:id])
    end 

    def feed 
    end 

    def new 
        @disable_nav = true
        @user = User.new
    end 

    def back 
        Back.find_or_create_by(backer_id:session[:id],backee_id:params[:id])
        redirect_to user_path(params[:id])
    end 

    def forget 
        back = Back.find_by(backer_id:session[:id],backee_id:params[:id])
        Back.destroy(back.id)
        redirect_to user_path(params[:id])
    end 

    def activity 
        @snaps = @user.snaps
        @slaps = @user.slaps
        @comments = @user.comments
        @posts = @user.posts
        
    end 


    def create 
        new_user = User.new(user_params)

        if new_user.save && user_params[:password] == user_params[:password_confirmation]
            session[:id] = new_user[:id]
            redirect_to feed_path(new_user)
        else 
            redirect_to new_user_path
        end 
    end 


    private 
    
    def user_params 
        params.require(:user).permit(:username, :password, :password_confirmation)
    end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slaps_helper.rb
module SlapsHelper
end

app/helpers/snaps_helper.rb
module SnapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<body class="body">
<div class="content">
<img src='<%=@post.image_url%>' alt="Random Image">

<%=form_with model:@comment do |f|%>

  <div class="form-group">
  <%=f.text_field :content%>
  </div>

<div class="form-group">
  <%=f.hidden_field :post_id, value:"#{@post.id}"%>
  <%=f.submit value:"Edit Comment", class: "btn btn-success"%>
</div>

 <%end%>
 </div>
 </body>

app/views/posts/edit.html.erb
<body class="body">
<div class="content">
<%=form_with model:@post do |f|%>
<%=f.label :image_url%>
<%=f.text_field :image_url%>
<%=f.label :description%>
<%=f.text_field :description%>
<%=f.collection_select :genre_id, Genre.all, :id, :style%>
<%=f.submit%>
<%end%>
</div>
</body>

app/views/posts/index.html.erb
<body class="body">
<div class="content" > 
        <h1 >Explore</h1>
        <br>

                <%@posts.each do |post|%>
                    <label > <h4> <strong><%=link_to post.user_name, user_path(post.user) %></strong> </h4></label> 
                    
                

                    <p><img src='<%=post.image_url%>' alt="Random Image"></p>

                    <p>Snaps:<%=" "+ post.snap_number%><%=" "%>Slaps:<%=" "+post.slap_number%></p>

                    <%if !post.snapped_user?(@user) && !post.slapped_user?(@user)  %>
                        <%= button_to "Snap",  {controller: :snaps, action:"create", post_id:post.id, origin:posts_path}, :method => :post, class: "btn   btn-success"%> <br>
                        <%= button_to "Slap", {controller: :slaps, action:"create", post_id:post.id, origin:posts_path}, :method => :post, class: "btn   btn-danger"%> <br>

                    <%elsif post.snapped_user?(@user)%>
                        <%= button_to "Unsnap","/snaps/:id", controller: :snaps, action:"destroy",params:{post_id:post.id,origin:posts_path},method: :delete, class: "btn   btn-success"%> <br>

                    <%elsif post.slapped_user?(@user)%>
                        <%= button_to "Unslap", "/slaps/:id", controller: :snaps, action:"destroy", params:{post_id:post.id, origin:posts_path}, method: :delete, class: "btn   btn-danger"%> <br>
                    <%end%>

                    <p><%=post.description%></p>

                    <%= button_to "View Post", post_path(post), controller:'posts', action:'show', method:'get',class:"btn btn-success"%> 
                    
                    <br>
                <%end%>

</div>
</body>

app/views/posts/new.html.erb
<body class="body">
  <div class="content">
    <%=form_with model:@post do |f|%>

      <div class="form-group">
        <%=f.label :image_url %>
        <%=f.text_field :image_url, class: "form-control"%>
      </div>
      <div class="form-group">
          <%=f.label :description %>
          <%=f.text_field :description, class: "form-control"%>
      </div>

    <div>
        <%=f.collection_select :genre_id, Genre.all, :id, :style%>
        <%=f.submit "Create Post", class: "btn btn-default "%>
    </div>
    <%end%>
  </div>
</body>

app/views/posts/show.html.erb
<body class="body">

<div class="content">

<label> <h3> <strong><%=link_to @post.user_name.capitalize, user_path(@post.user)%></strong> </h3> </label>

<p><img src='<%=@post.image_url%>' alt="Random Image"></p>

<p>Snaps:<%=" "+ @post.snap_number%><%=" "%>Slaps:<%=" "+@post.slap_number%></p>

<%if !@post.snapped_user?(@user) && !@post.slapped_user?(@user)  %>
        <%= button_to "Snap", {controller: :snaps, action:"create", post_id:@post.id, origin:post_path(@post)}, :method => :post, class: "btn  btn-success"%> <br>
        <%= button_to "Slap", {controller: :slaps, action:"create", post_id:@post.id, origin:post_path(@post)}, :method => :post, class: "btn  btn-danger"%> <br>

    <%elsif @post.snapped_user?(@user)%>
        <%= button_to "Unsnap","/snaps/:id", controller: :snaps, action:"destroy",params:{post_id:@post.id,origin:post_path(@post)},method: :delete, class: "btn  btn-success"%> <br>

    <%elsif @post.slapped_user?(@user)%>
        <%= button_to "Unslap", "/slaps/:id", controller: :snaps, action:"destroy", params:{post_id:@post.id, origin:post_path(@post)}, method: :delete, class: "btn btn-danger"%> <br>

<%end%>

<p><%=@post.description%></p>

<%@post.comments.each do |comment|%>
    <li><%="#{comment.user_name}" + ": " + comment.content%></li>
    <%if @user == comment.user%>
    <%= button_to "Edit Comment", edit_comment_path(comment), controller:'comments', action:'edit', method:'get', class: "btn   btn-success"%> <br>
    <%= button_to "Delete Comment", {controller: :comments, action:"destroy", id:comment.id, post_id:@post.id}, :method => :delete, class: "btn  btn-danger"%> <br>
    <%end%>
<%end%>

<br>

<%=form_with url:comments_path {controller:comments} do |f|%>
<%=f.text_field :content, placeholder:"Add a comment"%>
<%=f.hidden_field :post_id, value:"#{@post.id}"%>
<%=f.submit value:"Post Comment",class: "btn   btn-success"%>
<%end%>

</div>

</body>

app/views/users/activity.html.erb
<body class="body">

    <div class="content">
        <h1><%=@user.username%></h1>

        <h2>Backs</h2>

        <%@user.backers.each do |backer|%>  
            <li><%=backer.username + " "%>backed you</li>
        <%end%>

        <%@user.backees.each do |backee|%>
            <li>You backed<%=" "%><%=backee.username%></li>
        <%end%>

        <h2>Snaps</h2>

        <%@snaps.each do |snap|%>
            <li><%=link_to (snap.post_user_name + "'s post"), post_path(snap.post)%></li>
        <%end%>

        <h2>Slaps</h2>

        <%@slaps.each do |slap|%>
            <li><%=link_to (slap.post_user_name + "'s post"), post_path(slap.post)%></li>
        <%end%>

        <h2>Comments</h2>
        <%@comments.each do |comment|%>
            <li><%=link_to (comment.post_user_name + "'s post"), post_path(comment.post)%></li>
            <ul>
                <li><%=comment.content%></li>
            </ul>
            <br>
        <%end%>
        
    </div>
</body>

app/views/users/feed.html.erb
<body class="body">
    <div class="content">
        <h1>My Feed</h1>
        <%@user.posts.each do |post|%>
            <label><strong><%=link_to post.user_name, user_path(post.user)%></strong></label>
            
            <p ><img src='<%=post.image_url%>' alt=“Random Image”></p>

            <p>Snaps:<%=post.snap_number + " "%>Slaps:<%=post.slap_number%> </p>

            <%if !post.snapped_user?(@user) && !post.slapped_user?(@user)  %>
                <%= button_to "Snap", {controller: :snaps, action:"create", post_id:post.id, origin:feed_path}, :method => :post,class: "btn  btn-success"%> <br>
                <%= button_to "Slap", {controller: :slaps, action:"create", post_id:post.id, origin:feed_path}, :method => :post,class: "btn  btn-danger"%> <br>

            <%elsif post.snapped_user?(@user)%>
                <%= button_to "Unsnap","/snaps/:id", controller: :snaps, action:"destroy",params:{post_id:post.id,origin:feed_path},method: :delete,class: "btn btn-success"%> <br>

            <%elsif post.slapped_user?(@user)%>
                <%= button_to "Unslap", "/slaps/:id", controller: :snaps, action:"destroy", params:{post_id:post.id, origin:feed_path}, method: :delete,class: "btn  btn-danger"%> <br>

            <%end%>
            <p><%=post.description%></p>

            <%= button_to "View Post", post_path(post), controller:'posts', action:'show', method:'get',class:"btn btn-success"%> <br>
            
            <br>
            
        <%end%>

        <%@user.backee_posts.each do |post|%>
            <label><strong><%=link_to post.user_name, user_path(post.user)%></strong></label>
            
            <p ><img src='<%=post.image_url%>' alt=“Random Image”></p>

            <p>Snaps:<%=post.snap_number + " "%>Slaps:<%=post.slap_number%> </p>

            <%if !post.snapped_user?(@user) && !post.slapped_user?(@user)  %>
                <%= button_to "Snap", {controller: :snaps, action:"create", post_id:post.id, origin:feed_path}, :method => :post,class: "btn  btn-success"%> <br>
                <%= button_to "Slap", {controller: :slaps, action:"create", post_id:post.id, origin:feed_path}, :method => :post,class: "btn  btn-danger"%> <br>

            <%elsif post.snapped_user?(@user)%>
                <%= button_to "Unsnap","/snaps/:id", controller: :snaps, action:"destroy",params:{post_id:post.id,origin:feed_path},method: :delete,class: "btn btn-success"%> <br>

            <%elsif post.slapped_user?(@user)%>
                <%= button_to "Unslap", "/slaps/:id", controller: :snaps, action:"destroy", params:{post_id:post.id, origin:feed_path}, method: :delete,class: "btn  btn-danger"%> <br>

            <%end%>
            <p><%=post.description%></p>

            <%= button_to "View Post", post_path(post), controller:'posts', action:'show', method:'get',class:"btn btn-success"%> 
            
            <br>
            
        <%end%>
    </div>
</body>

app/views/users/new.html.erb
<body class="body">
    <div class="content">

      <%= form_with model:@user do |f| %> 

        <div class="form-group">
          <%= f.label :username  %>
          <%= f.text_field :username, class: "form-control"%>  <br>
        </div>

          <br>

        <div class="form-group">
          <%= f.label :password  %>
          <%= f.password_field :password, class: "form-control" %> <br>
        </div>

          <br>

        <div class="form-group">
          <%= f.label :password_confirmation  %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
          <%= f.submit "Create new user", class: "btn btn-primary" %> <br>
        </div>

      <%end  %>
    </div>
</body>

app/views/users/show.html.erb
<body class="body">
<div class="content">
<h1><%=@profile.username.capitalize%></h1>

<%if @user == @profile %>
    
<%elsif @user.backed_profile?(@profile)%>
    <h2 style="color:green">Backed</h2>
    <%= button_to "Forget this artist", forget_path, controller:"users",action:"forget",method:"post", id:@user.id, class: "btn btn-success "%> <br>
<%else%>
    <%= button_to "Back this artist", back_path, controller:"users",action:"back",method:"post", id:@user.id, class: "btn btn-info"%> <br>
<%end%>

<br>

<%@profile.posts.each do |post|%>

    <label> <h4> <strong><%=link_to post.user_name, user_path(post.user)%></strong> </h4> </label>

    <p><img src='<%=post.image_url%>' alt="Random Image"></p>

    <p>Snaps:<%=" "+ post.snap_number%><%=" "%>Slaps:<%=" "+post.slap_number%></p>

    <%if !post.snapped_user?(@user) && !post.slapped_user?(@user)  %>
        <%= button_to "Snap", {controller: :snaps, action:"create", post_id:post.id, origin:user_path(@profile)}, :method => :post, class: "btn btn-success"%> <br> 
        <%= button_to "Slap", {controller: :slaps, action:"create", post_id:post.id, origin:user_path(@profile)}, :method => :post, class: "btn btn-danger"%> <br>

    <%elsif post.snapped_user?(@user)%>
        <%= button_to "Unsnap","/snaps/:id", controller: :snaps, action:"destroy",params:{post_id:post.id,origin:user_path(@profile)},method: :delete, class: "btn btn-success"%> <br>

    <%elsif post.slapped_user?(@user)%>
        <%= button_to "Unslap", "/slaps/:id", controller: :snaps, action:"destroy", params:{post_id:post.id, origin:user_path}, method: :delete, class: "btn btn-danger"%> <br>
    <%end%>

    <%if @user == @profile %>
        <%= button_to "Edit Post", edit_post_path(post), controller:"posts",action:"edit",method:"get", class: "btn btn-success"%> <br>
        <%= button_to "Delete Post", {controller: :posts, action:"destroy", id:post.id}, :method => :delete, class: "btn btn-danger"%> <br>
    <%end%>

    <p><%=post.description%></p>

    <%= button_to "View Post", post_path(post), controller:'posts', action:'show', method:'get', class: "btn btn-default btn-success"%> <br>

    <br>

<%end%>

</div>
</body>