config/routes.rb
Rails.application.routes.draw do\

  #sign in 
  get '/sign_in', to: "sessions#sign_in"
  post '/sessions', to: "sessions#create"
  delete '/sessions', to: "sessions#destroy"

  #user specific pages 
  get '/:id/feed', to: 'users#feed', as: "feed"
  get '/:id/activity', to: 'users#activity', as: "activity"
  
  #follow someone
  post "/users/:id", to: "users#back", as: "back"

  #unfollow someone
  post "users/:id/forget", to: "users#forget", as: "forget"
  
  resources :comments
  resources :slaps
  resources :snaps
  resources :genres
  resources :posts
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/back.rb
class Back < ActiveRecord::Base
    belongs_to :backer, foreign_key: "backer_id", class_name: "User"
    belongs_to :backee, foreign_key:"backee_id", class_name: "User"

    def backer_name 
        self.backer.username
    end 

    def backee_name
        self.backee.username
    end 
end 

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user 
    belongs_to :post 

    def user_name
        self.user.username 
    end 

    def post_user_name
        self.post.user.username
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :posts 
    has_many :users, through: :posts 
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :genre
    has_many :comments
    has_many :snaps
    has_many :slaps 
    has_many :backs

    def user_name
        self.user.username
    end 

    def snap_number
        self.snaps.count.to_s
    end 

    def slap_number
        self.slaps.count.to_s
    end 

    def snapped_users
        self.snaps.collect{|snap| snap.user}
    end 

    def snapped_user?(user)
        self.snapped_users.include?(user)
    end 

    def slapped_users
        self.slaps.collect{|slap| slap.user}
    end 

    def slapped_user?(user)
        self.slapped_users.include?(user)
    end
end

app/models/slap.rb
class Slap < ApplicationRecord
    belongs_to :user
    belongs_to :post

    def post_user_name
        self.post.user.username
    end

end

app/models/snap.rb
class Snap < ApplicationRecord
    belongs_to :user
    belongs_to :post

    def post_user_name
        self.post.user.username
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :genres, through: :posts
    has_many :comments
    has_many :snaps
    has_many :slaps 
    has_many :backs
    
    has_many :backer_backs, foreign_key: :backee_id, class_name: "Back"
    has_many :backers, through: :backer_backs, source: :backer

    has_many :backee_backs, foreign_key: :backer_id, class_name: "Back"
    has_many :backees, through: :backee_backs, source: :backee 
    has_secure_password


    def backee_posts
        self.backees.collect{|user| user.posts}.flatten
    end 

    def backed_profile?(profile)
        self.backees.include?(profile)
    end 


end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticated?
    before_action :current_post, only: [:show,:edit,:update]

    def index
        @posts = Post.all
    end 

    def show 
    end 

    def new 
        @post = Post.new
    end 

    def create 
        @user.posts.build(post_params).save
        redirect_to user_path(@user)
    end 

    def edit 
    end 

    def update 
        @post.update(post_params)
        redirect_to user_path(session[:id])
    end 

    def destroy 
        Post.destroy(params[:id])
        redirect_to user_path(session[:id])
    end 


    def current_post
        @post = Post.find(params[:id])
    end 

    private

    def post_params
        params.require(:post).permit(:image_url,:description,:genre_id)
    end 

end

app/controllers/slaps_controller.rb
class SlapsController < ApplicationController
    before_action :authenticated?
   
    def create 
        Slap.find_or_create_by(user_id:@user.id,post_id:params[:post_id])
        redirect_to params[:origin]
    end 

    def destroy
        slap = Slap.find_by(post_id:params[:post_id],user_id:@user.id)
        Slap.destroy(slap.id)
        redirect_to params[:origin]
    end 

end

app/controllers/snaps_controller.rb
class SnapsController < ApplicationController
    before_action :authenticated?
   
    def create 
        Snap.find_or_create_by(user_id:@user.id,post_id:params[:post_id])
        redirect_to params[:origin]
    end 

    def destroy
        snap = Snap.find_by(post_id:params[:post_id],user_id:@user.id)
        Snap.destroy(snap.id)
        redirect_to params[:origin]
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticated?, only: [:feed, :show, :activity]

    def show
        @profile = User.find(params[:id])
    end 

    def feed 
    end 

    def new 
        @disable_nav = true
        @user = User.new
    end 

    def back 
        Back.find_or_create_by(backer_id:session[:id],backee_id:params[:id])
        redirect_to user_path(params[:id])
    end 

    def forget 
        back = Back.find_by(backer_id:session[:id],backee_id:params[:id])
        Back.destroy(back.id)
        redirect_to user_path(params[:id])
    end 

    def activity 
        @snaps = @user.snaps
        @slaps = @user.slaps
        @comments = @user.comments
        @posts = @user.posts
        
    end 


    def create 
        new_user = User.new(user_params)

        if new_user.save && user_params[:password] == user_params[:password_confirmation]
            session[:id] = new_user[:id]
            redirect_to feed_path(new_user)
        else 
            redirect_to new_user_path
        end 
    end 


    private 
    
    def user_params 
        params.require(:user).permit(:username, :password, :password_confirmation)
    end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slaps_helper.rb
module SlapsHelper
end

app/helpers/snaps_helper.rb
module SnapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href=<%=feed_path(@user)%>>
  <%= image_tag("logo.png")%>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/posts">Explore <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%=new_post_path%>>New Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Me
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=<%=user_path(@user)%>>Portfolio</a>
          <a class="dropdown-item" href=<%=activity_path(@user)%>>Activity</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="">
            <%= button_to "Logout", "/sessions", controller:'sessions', action:'destroy', method:'delete',class: "btn   btn-danger"%>
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtWalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' unless @disable_nav %>
    <%= yield %>
  </body>
</html>